---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/instance: grafana
patchesStrategicMerge:
  - patches/env.yaml
  - patches/postgres.yaml
