apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    adminUser: ENC[AES256_GCM,data:5iOg1A==,iv:rDi82cxRfdcXotOU4F9Q9VktH881rCG1QNCtF6kcg4A=,tag:UUGIieYu2buf7lSqXL31BQ==,type:str]
    adminPass: ENC[AES256_GCM,data:6F4hzVh4I7Hq7xh5l1Ls8K1Q0FY=,iv:qffhjDt29WRyDGQ28zNMaFE9WACujwT9hoNZ2UQaS7I=,tag:JWU2rIy8wj3dKGDyOlGayQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1FFWFM0NWxyME45bGlE
            SldYK3hLRW11TXBMck1ra1Z3WTh2cldnT1RjCm5kSWE3MXJ6NnB5Wk9FUGlMbUZy
            ZWk1bjluc0dyL1NCeWUzZC92aC9yOEkKLS0tIFFEbVFoM29lU3EvdEtjUlJBRU5a
            V3NaYUtVZ2E1Qk5zZlYzdnYrenFQMmMKmXpDjm6XpQoUzewnderf6193hjJ1Z4n0
            rstLjFu8dx7zUOWTDwjBFc1gvH5ZAKUxwxYJrBTh8MsofnuZldcB8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:35:13Z"
    mac: ENC[AES256_GCM,data:db9MSNaq0sQ2Ez+FpyY1JF+HJ8ZG8Lc/B/3ZbqeoOKPASSuSR3WGQID4RWH80vTE8lpYcBOyMQNYc7fSSQdx0+Df6A+JxXjbFZEohrAIDc1mBA9Zo22HU7du3/AuI20G9qPFcrKjHPNa2QLKZZHPtYrA0/GwwyXs9yIOrhNX8SA=,iv:0GwZZfGjoxJMs9V9FwdNZ0WRWKZqzGmW6nXXJfAdyNE=,tag:lSZqmjd1MhfjxrCAEQgcPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:hu3ebQ==,iv:Nv7oZoi0wMN/qBav/e81EKyyOHXdpYMhWnk8zzWkMws=,tag:2LV5etNrItcqRslaX/IWKg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:R5W/LaVOLqmmy4AC88Tz1E63Tng=,iv:YVfuOprFdvILqQnG1OYDrmawSQyyYwXacwlK3EuAod4=,tag:Or9yeAS1RvqNDriQIysJeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1FFWFM0NWxyME45bGlE
            SldYK3hLRW11TXBMck1ra1Z3WTh2cldnT1RjCm5kSWE3MXJ6NnB5Wk9FUGlMbUZy
            ZWk1bjluc0dyL1NCeWUzZC92aC9yOEkKLS0tIFFEbVFoM29lU3EvdEtjUlJBRU5a
            V3NaYUtVZ2E1Qk5zZlYzdnYrenFQMmMKmXpDjm6XpQoUzewnderf6193hjJ1Z4n0
            rstLjFu8dx7zUOWTDwjBFc1gvH5ZAKUxwxYJrBTh8MsofnuZldcB8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:35:13Z"
    mac: ENC[AES256_GCM,data:db9MSNaq0sQ2Ez+FpyY1JF+HJ8ZG8Lc/B/3ZbqeoOKPASSuSR3WGQID4RWH80vTE8lpYcBOyMQNYc7fSSQdx0+Df6A+JxXjbFZEohrAIDc1mBA9Zo22HU7du3/AuI20G9qPFcrKjHPNa2QLKZZHPtYrA0/GwwyXs9yIOrhNX8SA=,iv:0GwZZfGjoxJMs9V9FwdNZ0WRWKZqzGmW6nXXJfAdyNE=,tag:lSZqmjd1MhfjxrCAEQgcPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1FFWFM0NWxyME45bGlE
            SldYK3hLRW11TXBMck1ra1Z3WTh2cldnT1RjCm5kSWE3MXJ6NnB5Wk9FUGlMbUZy
            ZWk1bjluc0dyL1NCeWUzZC92aC9yOEkKLS0tIFFEbVFoM29lU3EvdEtjUlJBRU5a
            V3NaYUtVZ2E1Qk5zZlYzdnYrenFQMmMKmXpDjm6XpQoUzewnderf6193hjJ1Z4n0
            rstLjFu8dx7zUOWTDwjBFc1gvH5ZAKUxwxYJrBTh8MsofnuZldcB8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:35:13Z"
    mac: ENC[AES256_GCM,data:db9MSNaq0sQ2Ez+FpyY1JF+HJ8ZG8Lc/B/3ZbqeoOKPASSuSR3WGQID4RWH80vTE8lpYcBOyMQNYc7fSSQdx0+Df6A+JxXjbFZEohrAIDc1mBA9Zo22HU7du3/AuI20G9qPFcrKjHPNa2QLKZZHPtYrA0/GwwyXs9yIOrhNX8SA=,iv:0GwZZfGjoxJMs9V9FwdNZ0WRWKZqzGmW6nXXJfAdyNE=,tag:lSZqmjd1MhfjxrCAEQgcPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
