apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:A/CNHg==,iv:/3PKlFR8D0K1H/YTVSMPOjYQFQEImfFI/kipP5kEI2M=,tag:yA7YLVNgptDLMIz3aIWO5A==,type:str]
    admin-password: ENC[AES256_GCM,data:K32WykY/ZHmIOKWhULjbqscgjyw=,iv:u1GfYk5ScByTamtVgfIM4561PB/ERrkYYFyWKINLWSY=,tag:XpGn1eSNgPRCdw4dsnDrNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydzVzRzlHOGxMM0JLLzZx
            N0xZaWRnWWlRRnlRY1BNK2lZREliMzhtYTBBCmJ1K21XSi9pODIzREpWRTduR054
            K2pYcFRJcDE1a2Eyb1ZodGxGZVBiM1kKLS0tIGlGTm03eHF3TUJrZ2lJV0N0WXFr
            dlQ4NmpjVDRIbjR2akt2dGtRKzFuMEUKUBjOtdj4sVyaGBVK3KPanYnH4fzDpNOu
            9iNVPWQmVZvysvf5jMKD28AqMPZ/DBu3Au81l5SqTHF4kOcy/WYaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-17T04:32:53Z"
    mac: ENC[AES256_GCM,data:+LV+i2IbRWmEc3uQAxYGnxakUxUK9Xf8vsu7qIPE/JPu/MU7eywlc2Igd7E46xOYt+o7YcoTCPDkDFys2+3Kvwlvhdk44joVhgN2adUyphG9ddiM9yuuQbcVWou/U1EpY9iW4S4TpvD6OlSh4C0tvSfjEOwgc3wCOOsXS/x1B+0=,iv:GL7lzaX9HvJI5G/bQ1MyS5sfdP2MsEXnQhJLLACfq6I=,tag:EX2Coty6IQQp/odgpqm6Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:Tmeoyg==,iv:PCY3ORkgkMMS0hnQDHW0BlpyJahuKABEolyAmoPE46w=,tag:5nM3+PuveC79Et2gF84fSg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:jD0M1R9Stz0JtM5WoSSUW8ulPJE=,iv:UjBLyoRgUNPxKPRzll8UELK7OgKhY6HZsamUmoPDAuk=,tag:qjCWcbHFZ8C4ITxkjpAR7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydzVzRzlHOGxMM0JLLzZx
            N0xZaWRnWWlRRnlRY1BNK2lZREliMzhtYTBBCmJ1K21XSi9pODIzREpWRTduR054
            K2pYcFRJcDE1a2Eyb1ZodGxGZVBiM1kKLS0tIGlGTm03eHF3TUJrZ2lJV0N0WXFr
            dlQ4NmpjVDRIbjR2akt2dGtRKzFuMEUKUBjOtdj4sVyaGBVK3KPanYnH4fzDpNOu
            9iNVPWQmVZvysvf5jMKD28AqMPZ/DBu3Au81l5SqTHF4kOcy/WYaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-17T04:32:53Z"
    mac: ENC[AES256_GCM,data:+LV+i2IbRWmEc3uQAxYGnxakUxUK9Xf8vsu7qIPE/JPu/MU7eywlc2Igd7E46xOYt+o7YcoTCPDkDFys2+3Kvwlvhdk44joVhgN2adUyphG9ddiM9yuuQbcVWou/U1EpY9iW4S4TpvD6OlSh4C0tvSfjEOwgc3wCOOsXS/x1B+0=,iv:GL7lzaX9HvJI5G/bQ1MyS5sfdP2MsEXnQhJLLACfq6I=,tag:EX2Coty6IQQp/odgpqm6Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
