# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:T+e0uA==,iv:SISyBFI4qlR6gy+vLN+wMhGTr93XYAf0ARuLbDGNLwg=,tag:r4P7Vy1ejx1tBYhH05WzIQ==,type:str]
    admin-password: ENC[AES256_GCM,data:kzJDFM87Q3Dk+AFnnTuqxVXI6AM=,iv:vn7+FuZ33Dn5vh3HI4nkxu5Ta16JhZPHiKQpbNlnUp8=,tag:knM/S0wGhGIuohtpVHGBAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VkNHTyswT2IxaGM4d3p1
            KzB2dWNVWHhia2k0eEg5cTJPQncxNnpoWFFBCnNOaTBwVVNSUzZ3TmczTFhSR2Ru
            RlBVYW5vWVRQaVRlMmxJdmZ6eVNFcEkKLS0tIEpqTmV2dnZEQ1VFYk9WRTRJL1l2
            YWpBaUNwM01odjhZYTBHejZqNFUvajAKmOtWU4xtN9bVWhanhDPXup30Rfn0KW7L
            IfGcW1wKY0x5hT3nxsg1dIbO3ATmH5wE3nTv8KtHXPHCZjf9zmTmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T14:25:19Z"
    mac: ENC[AES256_GCM,data:oPcctsvcCLmoh2WW0ctJadmSY4qtDAYgPbB3PNxEwe9QXnzSEPPCaOfA1+ZGYxeiBEoaOxXgOhzG5Qlz6G4mh1kaIv8K7T53oAQa3fomqGN11Oc1dnYwhLMurmHtj4JBH5f0TNuF5bFqcn9/KiXDbbzpoHzwkM4Zn+l2WvSvkx0=,iv:WVdyJYxwIJcYRKLV9c5xlo4OvAmo6gUbmLAcRbD/vzM=,tag:th3qejRt3yDjm9fWl7MZ+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:9TiPwg==,iv:ZH6V/SLyoPiSbaW7gjgKJjcfkyoFVY0dYLs+ebiQmM4=,tag:+7hxhqeEauk2IlrMbLrHHg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:5cn7EhmOZEXljOmwwlBinD7Ju2c=,iv:UZKddZ079j2Du3+bAThEk9Z0XWE4v9XIEJyyne2lb3E=,tag:EZKkypAXfztv3t1urHdmNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VkNHTyswT2IxaGM4d3p1
            KzB2dWNVWHhia2k0eEg5cTJPQncxNnpoWFFBCnNOaTBwVVNSUzZ3TmczTFhSR2Ru
            RlBVYW5vWVRQaVRlMmxJdmZ6eVNFcEkKLS0tIEpqTmV2dnZEQ1VFYk9WRTRJL1l2
            YWpBaUNwM01odjhZYTBHejZqNFUvajAKmOtWU4xtN9bVWhanhDPXup30Rfn0KW7L
            IfGcW1wKY0x5hT3nxsg1dIbO3ATmH5wE3nTv8KtHXPHCZjf9zmTmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T14:25:19Z"
    mac: ENC[AES256_GCM,data:oPcctsvcCLmoh2WW0ctJadmSY4qtDAYgPbB3PNxEwe9QXnzSEPPCaOfA1+ZGYxeiBEoaOxXgOhzG5Qlz6G4mh1kaIv8K7T53oAQa3fomqGN11Oc1dnYwhLMurmHtj4JBH5f0TNuF5bFqcn9/KiXDbbzpoHzwkM4Zn+l2WvSvkx0=,iv:WVdyJYxwIJcYRKLV9c5xlo4OvAmo6gUbmLAcRbD/vzM=,tag:th3qejRt3yDjm9fWl7MZ+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
