# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:8H2UUQ==,iv:tsVZ2j9sofEy/akQtFwK7T65sACuQp7hxXQs+T2ICy8=,tag:bgJPx77R4tZNQSiLSN1sJw==,type:str]
    admin-password: ENC[AES256_GCM,data:ntPzJCU49GAT6UFUHs7F+Y7FDsc=,iv:7VMzS5HeZxeGgteSqAog8xGG6wj935ONFDD52r0wa6w=,tag:yn4ewtlod3bVt6pNG/l9EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd01uUzJHSEhpeWQxMGFG
            dnlTclZyZk1KcFpZZEtQSVJHZUlsaFBGL2hNClZjTy9lYVZQU09HOHJEYzluK2Fu
            M2IySHZLcDRlUmV3VHZ4Z3JGZ0tMNFEKLS0tIEE5QjlNSFlnZ0xrOEdRclNhNGtM
            L040WXFaMGljazRsYkRSeW42RmFQYUEKgOqcAi7Ag8qWcFZbObOZ/IQBIXmkUJgA
            mB0xlt76ZhZ65jEocsVhNvbT0q2nw06BaW5xN9EoFJbB13T9WmwW5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-17T00:13:44Z"
    mac: ENC[AES256_GCM,data:vjNn53rcUZBKJDx5RqLn5YOvopOu7Co4eTCCxVYtCE2f7fN6RHSzb3m8exnxiWT3Vh4z7nuz1q1TI60Zh6nX20fofi82mN3juJyD3xuErKchxqr1MWRsgkl9h8q1mZ2P4kfozc+4GwzgCGu73hoR+da3s2ALySxCRRwZW8duX2A=,iv:46poZRmzHTDzFlrZLIvVm3VJrbFfyQQOIXaY/1xBZGc=,tag:/P5YjA4opCY9aabAKT0l4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:U5iuDg==,iv:WRzsofwEZUhIoqYr2DkcDS8zjCv5VsLaVfPZ/hidMdM=,tag:GIA+uzDrztZKHsTETIDXOQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:0cGafbTqlvHdBZDktG+2T3lyffs=,iv:QL4EB99nNOGCGxY0jsbHZe4gQ/lZLpn9+yQgqH7Dei8=,tag:5xvQjbAVskNKVGFZGe9YJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd01uUzJHSEhpeWQxMGFG
            dnlTclZyZk1KcFpZZEtQSVJHZUlsaFBGL2hNClZjTy9lYVZQU09HOHJEYzluK2Fu
            M2IySHZLcDRlUmV3VHZ4Z3JGZ0tMNFEKLS0tIEE5QjlNSFlnZ0xrOEdRclNhNGtM
            L040WXFaMGljazRsYkRSeW42RmFQYUEKgOqcAi7Ag8qWcFZbObOZ/IQBIXmkUJgA
            mB0xlt76ZhZ65jEocsVhNvbT0q2nw06BaW5xN9EoFJbB13T9WmwW5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-17T00:13:44Z"
    mac: ENC[AES256_GCM,data:vjNn53rcUZBKJDx5RqLn5YOvopOu7Co4eTCCxVYtCE2f7fN6RHSzb3m8exnxiWT3Vh4z7nuz1q1TI60Zh6nX20fofi82mN3juJyD3xuErKchxqr1MWRsgkl9h8q1mZ2P4kfozc+4GwzgCGu73hoR+da3s2ALySxCRRwZW8duX2A=,iv:46poZRmzHTDzFlrZLIvVm3VJrbFfyQQOIXaY/1xBZGc=,tag:/P5YjA4opCY9aabAKT0l4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
