apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:/aNixw==,iv:6maPUVSbWfQ9jKixeM5ydFcUC/5PuLoN7Jfc92RvtOk=,tag:Xj8w91Dh/8yIZoJzBVKvbw==,type:str]
    admin-pass: ENC[AES256_GCM,data:I3KqyL/bizPwrcTq7G+PyyZLYCg=,iv:44wrCnGHxSJWpW/YJW9caGZ5pcR1TJACxoOqkvqGGQQ=,tag:1PMalD5UBEmAHS7Cs2kc0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1FFWFM0NWxyME45bGlE
            SldYK3hLRW11TXBMck1ra1Z3WTh2cldnT1RjCm5kSWE3MXJ6NnB5Wk9FUGlMbUZy
            ZWk1bjluc0dyL1NCeWUzZC92aC9yOEkKLS0tIFFEbVFoM29lU3EvdEtjUlJBRU5a
            V3NaYUtVZ2E1Qk5zZlYzdnYrenFQMmMKmXpDjm6XpQoUzewnderf6193hjJ1Z4n0
            rstLjFu8dx7zUOWTDwjBFc1gvH5ZAKUxwxYJrBTh8MsofnuZldcB8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:39:42Z"
    mac: ENC[AES256_GCM,data:IJl8NJsAQpWcjoFrqKoAlOmqtvoi2vasGhmwaCqEaToX8BOmjMc+Om/qXVU+pzfh6aFYvZrA2g7rVAqXwQuUAmO4bCqDYdGliSv2FrEIZZWrspB4HLu41zMtEexa0zW96/jT4l6ufOBaZQFtjGfttho2j9WBDqsF46asKrPzP1o=,iv:2IAO78/t5BRQQwv10dUMeIXaL7CLG1T76cfgg57RWHo=,tag:89iV4D6or6HyFIShHBYmGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:hu3ebQ==,iv:Nv7oZoi0wMN/qBav/e81EKyyOHXdpYMhWnk8zzWkMws=,tag:2LV5etNrItcqRslaX/IWKg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:R5W/LaVOLqmmy4AC88Tz1E63Tng=,iv:YVfuOprFdvILqQnG1OYDrmawSQyyYwXacwlK3EuAod4=,tag:Or9yeAS1RvqNDriQIysJeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1FFWFM0NWxyME45bGlE
            SldYK3hLRW11TXBMck1ra1Z3WTh2cldnT1RjCm5kSWE3MXJ6NnB5Wk9FUGlMbUZy
            ZWk1bjluc0dyL1NCeWUzZC92aC9yOEkKLS0tIFFEbVFoM29lU3EvdEtjUlJBRU5a
            V3NaYUtVZ2E1Qk5zZlYzdnYrenFQMmMKmXpDjm6XpQoUzewnderf6193hjJ1Z4n0
            rstLjFu8dx7zUOWTDwjBFc1gvH5ZAKUxwxYJrBTh8MsofnuZldcB8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:39:42Z"
    mac: ENC[AES256_GCM,data:IJl8NJsAQpWcjoFrqKoAlOmqtvoi2vasGhmwaCqEaToX8BOmjMc+Om/qXVU+pzfh6aFYvZrA2g7rVAqXwQuUAmO4bCqDYdGliSv2FrEIZZWrspB4HLu41zMtEexa0zW96/jT4l6ufOBaZQFtjGfttho2j9WBDqsF46asKrPzP1o=,iv:2IAO78/t5BRQQwv10dUMeIXaL7CLG1T76cfgg57RWHo=,tag:89iV4D6or6HyFIShHBYmGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1FFWFM0NWxyME45bGlE
            SldYK3hLRW11TXBMck1ra1Z3WTh2cldnT1RjCm5kSWE3MXJ6NnB5Wk9FUGlMbUZy
            ZWk1bjluc0dyL1NCeWUzZC92aC9yOEkKLS0tIFFEbVFoM29lU3EvdEtjUlJBRU5a
            V3NaYUtVZ2E1Qk5zZlYzdnYrenFQMmMKmXpDjm6XpQoUzewnderf6193hjJ1Z4n0
            rstLjFu8dx7zUOWTDwjBFc1gvH5ZAKUxwxYJrBTh8MsofnuZldcB8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:39:42Z"
    mac: ENC[AES256_GCM,data:IJl8NJsAQpWcjoFrqKoAlOmqtvoi2vasGhmwaCqEaToX8BOmjMc+Om/qXVU+pzfh6aFYvZrA2g7rVAqXwQuUAmO4bCqDYdGliSv2FrEIZZWrspB4HLu41zMtEexa0zW96/jT4l6ufOBaZQFtjGfttho2j9WBDqsF46asKrPzP1o=,iv:2IAO78/t5BRQQwv10dUMeIXaL7CLG1T76cfgg57RWHo=,tag:89iV4D6or6HyFIShHBYmGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
