apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    adminUser: ENC[AES256_GCM,data:4JOI9Q==,iv:MfDQKLvKArHiWCSIugvqzoygEujVMJ0Z9sBrCHctFoY=,tag:96GR7VOP04nWdbFCbUb9ag==,type:str]
    adminPass: ENC[AES256_GCM,data:jWAZd5FZCBSxm8O+t3DaBFhaT+E=,iv:3sWmB7BLg7Jb2Gz9EXI8EVzYPf7Eyb65ETHga4dYmdk=,tag:P4t3NaQ6eNp7glVor2YlUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydzVzRzlHOGxMM0JLLzZx
            N0xZaWRnWWlRRnlRY1BNK2lZREliMzhtYTBBCmJ1K21XSi9pODIzREpWRTduR054
            K2pYcFRJcDE1a2Eyb1ZodGxGZVBiM1kKLS0tIGlGTm03eHF3TUJrZ2lJV0N0WXFr
            dlQ4NmpjVDRIbjR2akt2dGtRKzFuMEUKUBjOtdj4sVyaGBVK3KPanYnH4fzDpNOu
            9iNVPWQmVZvysvf5jMKD28AqMPZ/DBu3Au81l5SqTHF4kOcy/WYaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:17:13Z"
    mac: ENC[AES256_GCM,data:2eiXCdCc6YpkBDTbfktHca7TykIoDgqrw1APTNWWgDufNv8GB2UGPARGzqGCSDLwL1PN+6NUqi5qmRlMheg52tJ70EVgYhzKIMlexn95XRvrViiMSl4VNKqA2R4EDBVerFlQbNZ4jGougK+g1Ph50qEhELKu8vU0nMJ++h45bZE=,iv:Mk7ySqtLz0xsEWuZGEX46TDKURg+A4gKqEfSPTP+ApQ=,tag:yjwjkrZ39QSTE/o3H0J7Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:RpGosA==,iv:XBHqsztDAalVMssFWqsr8ZuL4qigdj/A/Fzwp6sm43c=,tag:iF7CyT1k4N7wsomhOa2yFg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:CkZB50YnFehIZfGwHzlapG18trA=,iv:HB3GLtGKddJx4jxVji/ADIEhcAlBB8/lAAs6Wqcmcvg=,tag:CDuD6S1jxibKv6H/8SsJHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydzVzRzlHOGxMM0JLLzZx
            N0xZaWRnWWlRRnlRY1BNK2lZREliMzhtYTBBCmJ1K21XSi9pODIzREpWRTduR054
            K2pYcFRJcDE1a2Eyb1ZodGxGZVBiM1kKLS0tIGlGTm03eHF3TUJrZ2lJV0N0WXFr
            dlQ4NmpjVDRIbjR2akt2dGtRKzFuMEUKUBjOtdj4sVyaGBVK3KPanYnH4fzDpNOu
            9iNVPWQmVZvysvf5jMKD28AqMPZ/DBu3Au81l5SqTHF4kOcy/WYaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:17:13Z"
    mac: ENC[AES256_GCM,data:2eiXCdCc6YpkBDTbfktHca7TykIoDgqrw1APTNWWgDufNv8GB2UGPARGzqGCSDLwL1PN+6NUqi5qmRlMheg52tJ70EVgYhzKIMlexn95XRvrViiMSl4VNKqA2R4EDBVerFlQbNZ4jGougK+g1Ph50qEhELKu8vU0nMJ++h45bZE=,iv:Mk7ySqtLz0xsEWuZGEX46TDKURg+A4gKqEfSPTP+ApQ=,tag:yjwjkrZ39QSTE/o3H0J7Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydzVzRzlHOGxMM0JLLzZx
            N0xZaWRnWWlRRnlRY1BNK2lZREliMzhtYTBBCmJ1K21XSi9pODIzREpWRTduR054
            K2pYcFRJcDE1a2Eyb1ZodGxGZVBiM1kKLS0tIGlGTm03eHF3TUJrZ2lJV0N0WXFr
            dlQ4NmpjVDRIbjR2akt2dGtRKzFuMEUKUBjOtdj4sVyaGBVK3KPanYnH4fzDpNOu
            9iNVPWQmVZvysvf5jMKD28AqMPZ/DBu3Au81l5SqTHF4kOcy/WYaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T13:17:13Z"
    mac: ENC[AES256_GCM,data:2eiXCdCc6YpkBDTbfktHca7TykIoDgqrw1APTNWWgDufNv8GB2UGPARGzqGCSDLwL1PN+6NUqi5qmRlMheg52tJ70EVgYhzKIMlexn95XRvrViiMSl4VNKqA2R4EDBVerFlQbNZ4jGougK+g1Ph50qEhELKu8vU0nMJ++h45bZE=,iv:Mk7ySqtLz0xsEWuZGEX46TDKURg+A4gKqEfSPTP+ApQ=,tag:yjwjkrZ39QSTE/o3H0J7Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
