---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-ddns
  - echo-server
  - external-dns
  # - external-services
  - ingress-nginx
  - k8s-gateway
  - metallb
  - omada
  - tigera-operator
  - uptimerobot-heartbeat
