---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: networking
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens19",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.89.0/24",
        "range_start": "192.168.89.100",
        "range_end": "192.168.89.200"
      }
    }'
