---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: networking
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens19",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.88.0/24",
        "rangeStart": "192.168.88.100",
        "rangeEnd": "192.168.88.200"
      }
    }'
