---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - charlie-haley-charts.yaml
  - cloudnative-pg-charts.yaml
  - emberstack-charts.yaml
  - external-dns-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - project-calico-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
