---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postfix
  namespace: web-tools
spec:
  privateKey:
    rotationPolicy: Always
  commonName: "smtp.${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "smtp.${SECRET_DOMAIN}"
  issuerRef:
    name: "${CLUSTER_ISSUER}"
    kind: ClusterIssuer
  secretName: "tls.smtp-relay"
