---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smtp-relay
  namespace: web-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: mail
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bokysan-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: smtp-relay
    config:
      general:
        ALLOWED_SENDER_DOMAINS: "${SECRET_DOMAIN}"
        RELAYHOST: "${SECRET_SMTP_RELAY}:${SECRET_SMTP_RELAY_PORT}"
      postfix:
        myhostname: &hostname "smtp.${SECRET_DOMAIN}"
        mynetworks: "${NETWORK_K8S_POD_CIDR},${NETWORK_K8S_SERVICE_CIDR},${NETWORK_K8S_HOST_CIDR}"
        always_add_missing_headers: yes
        smtpd_tls_cert_file: /tls/tls.crt
        smtpd_tls_key_file: /tls/tls.key
        smtpd_tls_ciphers: medium
        smtpd_tls_eecdh_grade: strong
        smtpd_tls_exclude_ciphers: EXPORT,LOW,MD5,aDSS,kECDHe,kDHd,kDHr,SEED,IDEA,RC2,RC4
        smtpd_tls_loglevel: 1
        smtpd_tls_mandatory_ciphers: medium
        smtpd_tls_mandatory_protocols: "!SSLv2, !SSLv3, !TLSv1, !TLSv1.1"
        smtpd_tls_protocols: "!SSLv2, !SSLv3, !TLSv1, !TLSv1.1"
        smtpd_tls_security_level: may
        tls_medium_cipherlist: "AES128+EECDH:AES128+EDH"
    persistence:
      enabled: true
      existingClaim: queue-pvc
    service:
      type: LoadBalancer
      externalIPs: ["${SVC_SMTP_RELAY_ADDR}"]
      externalTrafficPolicy: Local
      ports:
        tcp:
          port: "${SECRET_SMTP_RELAY_PORT}"
    extraVolumes:
      - name: tls
        secret:
          secretName: tls.smtp-relay
    extraVolumeMounts:
      - name: tls
        mountPath: /tls
    pod:
      annotations:
        secret.reloader.stakater.com/reload: *app
        configmap.reloader.stakater.com/reload: *app
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
