---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queue-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ceph-block
