---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queue-pvc
  namespace: home
  labels:
    app.kubernetes.io/name: &name smtp-relay
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ceph-block
