---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app csi-driver-nfs
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: v4.1.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    kubeletDir: /var/lib/kubelet
    controller:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      podAnnotations:
        k8s.v1.cni.cncf.io/networks: networking/macvlan-conf
      replicas: 3
      resources:
        csiProvisioner:
          limits:
            memory: 400Mi
          requests:
            cpu: 10m
            memory: 20Mi
          podAnnotations:
            k8s.v1.cni.cncf.io/networks: networking/macvlan-conf
        livenessProbe:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        nfs:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 20Mi
          podAnnotations:
            k8s.v1.cni.cncf.io/networks: networking/macvlan-conf
    node:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      podAnnotations:
        k8s.v1.cni.cncf.io/networks: networking/macvlan-conf
      resources:
        livenessProbe:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        nfs:
          limits:
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 20Mi
        nodeDriverRegistrar:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
