---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-node
  namespace: privacy
  labels:
    app.kubernetes.io/name: &name monero-node
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
