---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: kured
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    configuration:
      startTime: "3:00"
      endTime: "7:00"
      timeZone: ${TIMEZONE}
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
    metrics:
      create: true
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    extraEnvVars:
      - name: TZ
        value: ${TIMEZONE}
      - name: KURED_NOTIFY_URL
        valueFrom:
          secretKeyRef:
            name: pushover-kured
            key: pushover-webhook
