# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:O8fWrP7MZ8BX9jb27SM=,iv:fUO/MoV5PCw4iesbss6uJaCljeMmsS8DsyHQN3aosVo=,tag:gNBfNlCBit8P6Zy7mm7pzw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:OA81bJwOESeICNNmdzKkC1jACI0vXiLGFOWdUl078dMh+rUY/A==,iv:huXpE9U+ePdzXbR4mc7RZUYsnmrPZRm/wNXU4gnW+M8=,tag:5LFDPj7o699L9OTNt/S51A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YIR+l54M0I1z7CvjFhg=,iv:aZ42y+c8KPADL90FNFrq2ws7b0OCpcJQg45mIvuw5jI=,tag:cXGxbITzU1d38cO47ziZxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT0VHelB3WmphbHYwYnZ1
            c1dXTzN5V0tZM2laMWxrU0pLSU1rNDVRdzFVCmRYaDN6LzVxYmdtR0VPTmFNeDFi
            ajBmeWFSM3lPcWdkNTlER2IvekcxVzAKLS0tIDE5TG01TFprTHJoU3RXalBlOGdz
            VDRkbDdja2NPS2lZTlpMaVBueG5WZG8KeU+Kixdm1TK4pQDVaYbjVcu+meTW4GO2
            isW/bFfnq3JU6331IkE7B7K1ZRsnaUCo96Pfzhz6LjGBm+b/5H4Wpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-15T19:33:02Z"
    mac: ENC[AES256_GCM,data:MmwBDOff1LBOOK2lWNdiZ+5EwcAcfrIQvXI+qdfJJcHza2uuhXmLlW3Du+UTW63W+BQjgg+/5iT3GqFMUPQ7ieTwnZD0XbLaepn1zUdZwLrgq2P0u/kBThf3yjlyiKKaaRGmY2CCAZimqLv+qUTBS8c/vqMH+LKcDa32YtfAtTg=,iv:/93TY+rxMufVhn1/IPVqnAd9HvGJOM/u9tMcYDcL9+w=,tag:SLGXtAr1Tuhuvhd4JZz1OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
