---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
configMapGenerator:
  - name: omada-controller-dashboard
    files:
      - omada-controller-dashboard.json=https://github.com/charlie-haley/omada_exporter/blob/main/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
