# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: omada-exporter-secrets
    namespace: monitoring
stringData:
    site: ENC[AES256_GCM,data:ZW2Zu0SIMA==,iv:gznbV0dM80ZbbgYof6IuFROLPCiD0qzM6FJvZuhnfyw=,tag:W2r/yvn/f1UDwPahQTM+rA==,type:str]
    username: ENC[AES256_GCM,data:oO/Gzvu0qig=,iv:AM2CC2zUf2R6qG1OljIEv0npVtWomCRIjtYXi7UaF1s=,tag:r0hg7jNasAnJHJmRKiZceA==,type:str]
    password: ENC[AES256_GCM,data:auVGgILZei4ELgWFkGL/rhBhViI=,iv:Dyh+dqmGLwYignrHn6sWyoXpKSx3/EVfIlF/PGnL4Nk=,tag:iXlM1GJyAQqmtQ6gLJ558Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWTYzbm85dzIvcElRZG9s
            dWNHRERCek83SkdTQnBlZ01YcGQ3RnM0UW1FCmZNSXNxVUJWdHI2Y2g0VCszVTZE
            RGhvYnp0QnhTM1Avb2M2SkhPVEsvbUUKLS0tIElWdDM2UW5GZXdlQkNUU1ZTanQ4
            TGtNRHVWUkFxM1dFUlg4OVNFc1VXdGcK67szg90TDUJOuzzvOAdjE9oetSMTN+E8
            9t8EBs2cvrPRiqMlCzIpcnMtQ5vQqNvF2k9+BwS+KJ4Km4SB3StTyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-18T04:22:35Z"
    mac: ENC[AES256_GCM,data:vekUeSZEfNSX7NJ0hqAgIFgROtWrMZdpaplNg4lwcwAfV6mDNmXxG1e7DkHTu+0nvxtA9N8KrhZW8fK+X6mDRwcNUCPyFvZr6HtuLuu8ebz/Km8hOPy5G7yZatSeSt4fqolBd0z+4DSC+G8ouJLZGcSLKAJZqwAxtAKIHrjgEz4=,iv:9ix33qcicTJpc687jWwR9SVi2GlQqdAljum6dm1gsA8=,tag:9knuKxrFtW8djKNRb+ozgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
