apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: postgres
      namespace: databases
  values:
    global:
      nameOverride: *app
    image:
      repository: vaultwarden/server
      tag: 1.26.0-alpine
    controller:
      strategy: RollingUpdate
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
            protocol: TCP
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
        mountPath: /data
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 200Mi
    envFrom:
      - secretRef:
          name: vaultwarden-secret
    env:
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: pgo-cluster-pguser-vaultwarden
            key: uri
