---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app xteve
  namespace: media-servers
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: alturismo/xteve
      tag: latest@sha256:7885f2759c0da3c5f2c72b2e45ba4b602bdd7d6f04cc6abba201091f11c93a95
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_XTEVE_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 34400
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/app-root: /web
          hajimari.io/enable: "true"
          hajimari.io/icon: sports
        hosts:
          - host: &host "xteve.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
          - secretName: "${CLUSTER_CERT_SECRET}"
    persistence:
      config:
        enabled: true
        existingClaim: xteve-config
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
