---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.25.1
      sourceRef:
        kind: HelmRepository
        name: intel-charts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: intel-device-plugin-operator
      namespace: system
  values:
    name: intel-gpu-plugin
    # sharedDevNum: 2
    nodeFeatureRule: true