---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - pdu
  # - ups
configMapGenerator:
  - name: pdu-dashboard
    files:
      - pdu-dashboard.json=pdu/dashboard.json
  # - name: ups-dashboard
  #   files:
  #     - ups-dashboard.json=ups/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
