# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rGzlGKlDphDV2ciBEl0=,iv:mRgI6ssVORbaBmDqsuwaoi6UmirF8lmRfkMbEshNoFM=,tag:IEUu3BibcBQodtU+YJ/Rew==,type:str]
    api-key: ENC[AES256_GCM,data:qPFr7ORWMCQP5jTeONyk+SdCooPDX5QozAMMhr71MhnLAG+9mQ==,iv:8xjQNlUJWbRA32qraY1TdwnyF8giNrZvwzNQ6QRHhMs=,tag:XEz0cy0RX9NrdFOyQhzNdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIclhwL2d3N0xrdytMOGJU
            RElvR1E1djh2TUw2ZytWNmtxQUZCZWlFMzBzCnpGNDdwYjdmODV3T1IzMjFURzU4
            bnZ4a3RsQUp2c25WWWFoQUdYUDUxRGMKLS0tIGJlbFAwV0xlY2pSaG5meGpmbjVC
            NmxTVWM0dGc0MkRHNDBuVHVPQ2huM3MKL5HdjRLq0iCV7osQRNEDF/3xJrPOMob9
            z69I5IctzPRXMiEvOs/ndvaMoi/japA4YCxCe4apM6H0WArX8y2/Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-15T19:33:02Z"
    mac: ENC[AES256_GCM,data:jUirVhrkxRR7WacsC7FB2Miz4lg36T2uztU+iVx+ycqQpzuXji+qWNJTD+CCZ9Pnlfkkbg69reDqGOhmrGXqNk7hlkEoZWqye4UcTMdkQVZzLVEyStNlgnouVY/DtSm9f9ESvJbHdOpXZxGRHaHD19gpfuvNhiKJtHqkSZg68kA=,iv:MY2nl0Z5WiSCPxQXTr1BKgsA6WdmBxUeEYUuyY+OzkY=,tag:pV3wsE9n5xKPvdo4/KSRhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
