# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unpackerr
    namespace: default
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:HA2TQ/Ls/Vmrdvs/UHyWKUjPI+k=,iv:psDFwzEYwS49zaBXPJiPs+e9mgvUhLACx2DcGk2QMuI=,tag:PFHoKfGOUv2AWFk/zx/RyQ==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:y7DyRXIkzX0fXcYuE8w0IaxFNB0=,iv:9+pVuz1ajPjmxIGv23o/FFKywtAhxjZg0tfMPUOrvkc=,tag:wA0FhMz5k2Onb3o9R4lfgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQnBKUDRpNnFqaVk2KzFl
            ZDFITmZSRy84dS9Ud0dock5PdTJEamJJRlhVCjZqOEQ1dHdqV2s5NFp3NlNrSzRy
            dEtCSC8rL29QaGNHeElXK2hOSXI4NFEKLS0tIDdobVlmZ0tkb2c3bnNrMXVqdTVw
            OUlxT3NiQmxWNjcwSjR6NEtqZno2SEUKaqAj3wdGB4e+8ZtQQV7Sstz7iwoJPm9j
            I15W0RUXUTmEsS+n4x0InGSipei0L40Gqgms226tcqbbce3uL2TMgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-17T04:06:57Z"
    mac: ENC[AES256_GCM,data:Nffn4mMVkd04jJK800jczey5XgNkzYvCS3Hn/GvZzuyVybKEG7iPx61MBGJXHWQQr47eVIOdyn1CAOk/cKWtUiLxugiXy7wmqFvE0VJMmfgxrfGucMMBZYlcGYHJ+iTjI/fYIjkcbSU7Io93aL7sa7+bfIjtT+UjDiW7MvfVYCs=,iv:lZugvAu3YIvgsGsJZKw6dS2M8BLAyOUypl5O7C9FGz0=,tag:JcCvw6DU/pA78/bW8X5dXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
