---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Toronto
  CLUSTER_CERT: "wildcard-default-staging-cert"
  CLUSTER_CERT_SECRET: "wildcard-default-staging-cert-tls"
  METALLB_LB_RANGE: 192.168.10.70-192.168.10.79
  SVC_NGINX_ADDR: 192.168.10.70
  SVC_K8S_GATEWAY_ADDR: 192.168.10.71
  SVC_OMADA_ADDRESS: 192.168.10.72
  SVC_QBITTORRENT_ADDR: 192.168.10.73
