apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:B26ynVb5rTwH,iv:7tzEs2kLuLMv6TwJED6+l1gJSJvQD+0Rs9DIIUirni8=,tag:ipFJrMOBK1E+tK2U5nph4A==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:Iltoy1oARtk/2h0hG6c=,iv:qHyXYKlW7iUIZ0rQ/oR9fhIv6m7xpS93sJJCjuYwZYg=,tag:9EeRUeNK3Kxo9WyTweSHFw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kLluQM/JfHnZ2bS2mhY=,iv:F/zhge0goAr9XL6gHvbJDM6LNlTNLkg2jyRppKmk9LQ=,tag:AIwI91EgPxQn5m6MtzDVdQ==,type:str]
    SECRET_SMTP_RELAY: ENC[AES256_GCM,data:a9DBVUdYxqVItAU4gMJdgCdU,iv:W788v+3zLy1IXpp7/Q3LW+6QWAhAQyZD5c2jJpFutgE=,tag:CQZHAcM8fkl95amiDUVI4A==,type:str]
    SECRET_SMTP_RELAY_PORT: ENC[AES256_GCM,data:t8Nu,iv:2OPe/pdXGC3OuYESGdKc68wIK6OsE20p3cemRjLGoBI=,tag:o6YaCiNg3UK5eLt+CyVcZQ==,type:str]
    SECRET_SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:ryoGpRCVhV6D0C2zeXI=,iv:u/IJOb0rn/q1dANmw5rJQXzsaq3y/3hv5SFRmGRe770=,tag:8VFivCHVjpNg6xq/MFhX1A==,type:str]
    SECRET_SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:6whzXdInXOKPGJp8evtuXgpiMVw=,iv:lRXt83wGl4DbTiiHHFUiA9CZZa8y4SP45oziLRhxUkw=,tag:R9BnFr0w1xnczAw58yFyEA==,type:str]
    SECRET_DOH_QUERY: ENC[AES256_GCM,data:OhuRtS83/TJWCy7aOgaPoR6PtWpxYnH1oJTRYc4=,iv:P6Hb0qcdfVx5n3kzJctUKYf0spHG1YkphxEm+tp705E=,tag:Hft8Vv0fap8DIczou6LlqQ==,type:str]
    SECRET_OMADA_HOST: ENC[AES256_GCM,data:AfKCLy/5sepULP2By2rW3hP3XatnzaN9ER7guVCAmbhVOvjyIXZ5MiLKMacyXjNyevTGx1M=,iv:fOQs/UIqvW2wj/yExRkbshRwDdG+tpEeol2j093/e7k=,tag:Dmdp6mP+5EXS8sjNm8MVPw==,type:str]
    SECRET_OMADA_USERNAME: ENC[AES256_GCM,data:aJcgXK0NgmY=,iv:8ZVGZgQalkBPf6XJjEGtpeAlX9Q4AJWaEen0Vxip7PM=,tag:aYSsc2qVvmM6OeXkZry0gg==,type:str]
    SECRET_OMADA_PASSWORD: ENC[AES256_GCM,data:aD5PQt4/jde75mmATr9nCxnAP/k=,iv:6zD/6IjJVrjmwirqpSO2cX86kha8YGO6a8qmHCE7zwk=,tag:ug0gIChMoXOjJPaL76tIDg==,type:str]
    SECRET_KVM_USERNAME: ENC[AES256_GCM,data:Aws3/6E=,iv:OAX9Xo0oZZDf3LnPU+qzrZrk8g28UGVAA2mrVjLHJeM=,tag:XF+rFAia85S8ou3fEqxVmQ==,type:str]
    SECRET_KVM_PASSWORD: ENC[AES256_GCM,data:0R9FiKlw17m/UD0xUJY9mmOdjDc=,iv:8yuiWmA2FeBJSxbGEqURfzoRUQqHpXHC8fFR1ipEr9c=,tag:hSoRsXztwwEHSydH7qlJbw==,type:str]
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:Y0XJO0FpBkMW2V4iOZbYJtwe4NZXaHJMylHTTkal,iv:lf61w9D4qYAAd5ZdsGoX7W0zH8TBvLJiiEfWqThyFjE=,tag:DU96Kax0bPPD0cYmmZWUDA==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:43AV2fkpnYNBrntlsC5lsVwA57L8rBdR6HR6SG18,iv:ytTCwOfVzRNqOh9MvIJVdsrmpGfYlE/hZSsoqi59xJ4=,tag:19M5R3OYIHFu7GL2v4MK/A==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4EJ6kRwVMS7Gv8JbDV2sOE02FFmzYu44gJ+Exn3mFvb0ssgzP8VOMe96GOsxvO2ipDvuIp8LPABxikj5PgCWmw==,iv:LK+N9dMduBWgnGBq6/Q70+if3rYNaZISTm8WvHDOY5g=,tag:/Mi+fQBfXSYXaxWVnSwcGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVFVnTzl4cm9KUWExMEh0
            Ly9oRHpSUkVjOStFSHRzZlJNTUJham1jN1M0CmJUZEd6M0NKWENqeDdSVDU3L2hQ
            bDNSdWcwUWgrL3ZiVlhMWE53VUJ5TEkKLS0tIHM3U1VIOW9GcUZiT0ZPNExxYmVE
            OEthaHZ1OURGZzRTaFN2bWYrMG9xT00K7RoJB/qkyE057NeTUIlgZA42aepnnyC3
            CTBJQJr8XOPcbVJZEYoqg1Ix+RcWIyvghN+ZKfo5Uc4h1bPPpsDvDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-10T00:53:44Z"
    mac: ENC[AES256_GCM,data:d+e9lWYj/+GITd7omip9e2Y0NjsYIVt/p80yBTJA33MeHnMwq3EKGly5r8/O0vV8OCNA0IKElIz1quEs6JArpHehJPsexkm3T6EtLEEQiUMa5JZE5acZ9yGFOfPWIXjyd/X2MPo46nP1+ojAWtNG/B7qesmm3nytEKyAbitpkFc=,iv:XPxe6VKoB7M3PNSeaFNI4CQXojVtWBPFBtcqoS+ZlEA=,tag:4VB5mGjMmqXTrOwrjjXTLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
