---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: web-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      defaultEnable: false
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
          - secretName: "${SECRET_DOMAIN/./-}-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
