---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: web-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    hajimari:
      defaultEnable: false
      namespaceSelector:
        any: true
      customApps:
        - name: NAS
          url: https://nas01.${SECRET_DOMAIN}
          icon: nas
        - name: Router
          url: https://router01.${SECRET_DOMAIN}
          icon: router
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: 'https://discord.com'
            - name: Outlook
              url: 'http://outlook.com'
            - name: Teams
              url: 'https://teams.microsoft.com/'
        - name: Cloud
          links:
            - name: OneDrive
              url: 'https://onedrive.com'
        - name: Design
          links:
            - name: Awwwards
              url: 'https://awwwards.com'
            - name: Dribbble
              url: 'https://dribbble.com'
            - name: Muz.li
              url: 'https://medium.muz.li/'
        - name: Dev
          links:
            - name: Codepen
              url: 'https://codepen.io/'
            - name: Devdocs
              url: 'https://devdocs.io'
            - name: Devhints
              url: 'https://devhints.io'
        - name: Lifestyle
          links:
            - name: Design Milk
              url: 'https://design-milk.com/category/interior-design/'
            - name: Dwell
              url: 'https://www.dwell.com/'
            - name: Freshome
              url: 'https://www.mymove.com/freshome/'
        - name: Media
          links:
            - name: Spotify
              url: 'http://browse.spotify.com'
            - name: Trakt
              url: 'http://trakt.tv'
            - name: YouTube
              url: 'https://youtube.com/feed/subscriptions'
        - name: Reading
          links:
            - name: Instapaper
              url: 'https://www.instapaper.com/u'
            - name: Medium
              url: 'http://medium.com'
            - name: Reddit
              url: 'http://reddit.com'
        - name: Tech
          links:
            - name: TheNextWeb
              url: 'https://thenextweb.com/'
            - name: The Verge
              url: 'https://theverge.com/'
            - name: MIT Technology Review
              url: 'https://www.technologyreview.com/'
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
          - secretName: "${CLUSTER_CERT_SECRET}"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
