---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app nas01
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: nginx
  rules:
    - host: &host "nas01.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 443
  tls:
    - hosts:
        - *host
    - secretName: "${CLUSTER_CERT_SECRET}"
---
apiVersion: v1
kind: Service
metadata:
  name: &app nas01
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: nas01.${SECRET_PRIVATE_DOMAIN}.
  ports:
    - name: http
      port: &port 5001
      protocol: TCP
      targetPort: *port
