{
    "data": "ENC[AES256_GCM,data:EpaXBYlvsVHiC9lE/j72YifTwdFDeCX10eOBhLAHNQ1/CALcV8GBmg6QGpD7esFFbSdbh2bpil+L7v+IZceNeAD8eZQmnF7VWPNI8K5BBDmIWWZQkVRReomguNoxiVYicHlgIqjpN5/lO1ub8YaplRowtiDSt1FqGv49ivAHtvsTogkmAqij662Xq4dqYPv6vhhSQ2ut03AF7Psdv22JinYaWhQg/kvZdu/m72o+q9GmfBvSimzn1uxMIwmA3uhMUF3khEeJiihhGCSe2wLzTMAfazY2AA7rKiGD7IDr4CeHPo00,iv:YnpyPR8MyIXkjc9ik0WwrY3KFhZgngXiV5CAsRWHQ7Y=,tag:5l8TQ2JJaVlw2IZ3dt7GDQ==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzakk2aXNCZzdQdDc0VFhB\nS0VWQXRzeE00S0NJVFBPaDdaNUxMM2ltS3dzCkdVZkJCcEVZVFdHbElUUVVqU0ZR\ndDVTUGIzSk9uYXJTdUQwM3AvRWpkSWsKLS0tIDJhNlZHOGppNkwzdDZoRFp2ZnFO\nYUpQYitXbVpDSUdsTzFndlc0YVhkMVUKD0NXfspk5S0PlRlq+BRiUXBYT1jHgKQf\nq1A8WYibXvIy3C+QHbH5PnnaTvcjw2c9saEoqRCBI0xg2gOc6q8Kbw==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-10-23T11:41:50Z",
        "mac": "ENC[AES256_GCM,data:1E2Dz7ePJWwAdFBeoJrGmUh5YA71XKUbhqKMHTH0mXKid9y6sZwh7IX9UR8QxKEeykeTKsfDMFPX6a159p9pLBL8SEuREQZxZpPOG5aA07tbBe2iSDH1lcYtDQ/6TGtSHHGAHEDTcxXsHAP3V/YP9thmd34AS2mJowmV6Afa0h8=,iv:y4Ze1iJ5JqIDqtElUyl+5XI1U5e5x8CMlRR2W0oHGWU=,tag:aAHHF7cozf383UD4cxGUzQ==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
