{
	"data": "ENC[AES256_GCM,data:KIOEudTMUDjpm4czSgrmz+5NARzkWIHRXzvjoeBmE1eml6DOedmzS7IGVuXirc1hJOjp7Rz3XAuX5QQTQW+MUmqH+Ds7OAAQes6rpMuEjzeypncV5Au6lOkmTYJRy4nbzPqoGKq95nWPUNF/dg6ledn2xagjeQvvPO04x8oZWqYW90I38O97QWnAauqiTZtQaavsVpu/V9YW0u+qPfKpMknWQBQuhtD5Lo7/yELnVRMATfP3BFc+6jg6r72ySIHaEPBx3Zt5/zPTFXLj7HI6ygRHADdMDwGvDvLy8kOippm4BCoZbqqg54ionOrjmVpZA/YjJ3UrwXQ/FVbLY9V/xtTz/JguInGadh44eykIprFKkn/gSIU0v7niwwDW33Suz4N3JXy0474NRYDNEUFeNpcmZtdQ5Jk1CE1MFbdAwCy6LUM8e3V10ru8dCPkqjRCSM/s6fVDE3vUtuwyS/TD4aHgb6nNcsNcdfjuCtFwwR7TEp1pvhndjFQM9cSPHCugavopzZS9zli9YJRCAvdvkDwv2DUfXaO254og/psRpzIqTs+0zziFozBHQh71VEyM2SRZSw9O64jm21okadW0JpUxbaTki3rsVudPK3jodYDWOUsEH8bogiLPyxqbKOD6u5I70q+50i+RGgzxzlbnRl34C71f+rclCQ8mh4MEOs9j78NNAm7tS4J5LnEAzh9pkZ8T4OtqpTC77G2FE9XQ0I3EWVlxw9NcyJ4BXIdLV/Hpopmsg3iD8z9apsLWyXR6R7i0hKZcARlGQEzSR67s,iv:fv5KW2cQuF05C786XqnnL7wo7Ikr15Z/lzh20p2vvSs=,tag:2X9fhFAIubtJjKYWCSF9Ag==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRkVLU1puU1hCbjJEV240\ndk16eCtNU3UvQ1dzeDVwYUUwY3c4SDl3dTJJCk5COHBvWDdYSmhMYVRvRXVOZ3JT\nZEZKZFRuMHBoT3lHWGxvSUdNdWZZWTAKLS0tIGxDS0lTOEhJUFd5ZFgxMUQrcXlr\nUVkrTUEzR0l4VUt1NFRVMFc3ZkMvVkUKy1ncnu8Ssyk0ySCz/STpAMsCJH/l10Y7\nOo8LyefnkC/JVwXBZorrVpPs4luGdaveH3BdK1TTXyvP9WuaJaze5w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-11-03T22:05:34Z",
		"mac": "ENC[AES256_GCM,data:d92jQ2WqDzckh4bbbGsebm2+VcXUDQWtrDhKG/w/yYvVoRxBHtMbPA02LQX81Vpirj+To3euUEvYpTgF1wcFpGzId9al08/ScMBRTYaeVkyuaotj6G9FYoSnXqUMam+YnEQum+0q75a8zXGHsiHJ0ZDgY/shydTLKwOTU0FEVik=,iv:cVHsH1T4jbInwWka1fNpNnmp8K7mwinqCwwcgVwF3gA=,tag:uxYZ4fH6PYHMvXMdA1X2wA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}