{
    "data": "ENC[AES256_GCM,data:qSJLg5JqeMM+wpDiAs89u1Y/8FWJLWG/d9h2Pvec+cgUrDHpGSvkWMc2Ap2CexLmILhddnaezfxyqhEqoySaRraHIJbL2BZbmMa55fY5L6skgPWQnKzo8kQq19JSi0IvtjbCIxouG/W9tSu5DcljJCJ7vlCoY0Ze0zfkViSTMuQxua7gwwAcczI6OiMk1XwdawYn9tgowaaPKfRr4C4Q6twgUn5g+WtlmCxnOLWD4xrQ7pe89Kacw4gBENSfjUefQf4tsO9GHp0fa3YIRZywyke9T6C2CeA9JB7JNum8VglRxgFhm62CXq6Ha+iffCpO9qJyxV2empVwhsc+knvju0AY+rB60gLZny1lJ9AgBVO1Hj49GZASlNDre/9KJE8zhnTmyVxA4KAIqMxI2/50vEAY0ftWxsSv3Ck1GrD7sz6wJHoZ9sQ8sEIKulfEP3LvSCvfnbE1iRL4E4l0v2w+5AgqoJBgZPkBFZYNE+Ji1Xap802OXkFDpnlu4Yy5CuHYledqfe1tD9XLpvudR2lZO4KibTUNwEuUPw+pB5KVeVbilB+btUJPSX+fOYZKPpWFdr6YQ4fVTC+HHITTLhpyfhi0GD4nq8NyhqOXp8IoFmPa006KmIdaDwjXibM658hJQBa+DTOle8nVQCHdVSzqEICyxpnLHvglFkbRud+DNHOyf4qZqV74UiaFAhC0j9q6iP4XldYIu8/NJajyzcSUBhYXolUFx030l7iSwpPk3yQID2DBl5S2l1zMPlzLBy54B27i9RAHQrznN7Sns3Mc,iv:E8UjqP/VxIZGsn+yAvHDn8pU1tYSgJjchlcxbtVAOZo=,tag:I7JNPBFQmnFKFxZScRT4uA==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRkVLU1puU1hCbjJEV240\ndk16eCtNU3UvQ1dzeDVwYUUwY3c4SDl3dTJJCk5COHBvWDdYSmhMYVRvRXVOZ3JT\nZEZKZFRuMHBoT3lHWGxvSUdNdWZZWTAKLS0tIGxDS0lTOEhJUFd5ZFgxMUQrcXlr\nUVkrTUEzR0l4VUt1NFRVMFc3ZkMvVkUKy1ncnu8Ssyk0ySCz/STpAMsCJH/l10Y7\nOo8LyefnkC/JVwXBZorrVpPs4luGdaveH3BdK1TTXyvP9WuaJaze5w==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-10-23T11:39:40Z",
        "mac": "ENC[AES256_GCM,data:RI/ElHbGiGyD/10vQkmeqn8VnOpy0x7vdpwNGqWhOAq7OrlpWoJc5ANJY2YHIQgXSWy6v86FaWtxYx2SN7KSNoIZoMoisjlPQj1Xuw0LkYBTkYUARqpWfbGtkBe9zSLW7/N96PVwGJf9AZWAts6vnnCnOwGtbwb9xjdM5IIJDeU=,iv:UkS7up94F+Z0/NhZkKlxpRaIgTpidD96wbsgohgybKI=,tag:OxPMOcKSL0ka/suuOo9Qcg==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
