{
	"data": "ENC[AES256_GCM,data:pAgTHY9gJV86JMdh2XcjeTgpikXNP7KHlemR5ONuo00ZBbUH80maVq13JVhy+fEVY44uoQWBkgQAVecCz87qnJ8Lo/wrFR0oNnT6mZdNTpxtZ92LPiOqQlaAEts6YoQHKZ8Sqm0W4yR7FNlHHjtEtrdVmUQGcwWudnbVjPAI08oRUsxawToM+ckGg9SJNS8FpGNkmKTY+hRFpTsD8W5cW61J4fyUjL4tdVDE1vVvcozTSfwAYA16UiRQ9UuQI027oj11xmZwlaMJBOFp7Q32EteNlh5kv8mIiqn25qvNJeMyFWiaYn9DePuS6ByygKS6XbmRaVOoI2IQW+kscjYM4GpoJYmoE8dNn9+MKPdZmQWtfkyhGBkebuMPfKS7A3vCrA0yJfpdClJrCmGMOEe2iD57oP6zkBBFxToYvJ5sp3hdsHbKqwXo/O5OtPeDquoUmeBzYbR2DSxozPyqjiAyzt7Z+TcXA1ghXLUOc1/mUab3Kowh2jXlw6IAcJLYUdZrLdmd7paNS/PWZ4f4oXdm6Nj/P02nZqPYniMX+iy437nTF51MqcTMzJGyUe8pDl9aNhLx/UXQQcKK/TZMQax6Dc5Im0cAkF4uzbnnT/cRdE9C/BGPJ87bupok/wk9xavGqT5cheWw61ySqXmf/ng7dwTklRq6BAsKVCIjvLLw/A8nT7dP7ibH83OST8kfeq1HJXBM1tBXub1WFZhefJd/Yi7ELxImEgqsjLp5/aKUrylu6JZ6nddYzexsQUl0ky2BIp5eAqBqI48u/xFR8H8r5tP1YX9nkDFQMqOV+8s=,iv:AOSZVTY5HZmLn8zoNVuM+h/cWxA80OKmpqctopIs+wQ=,tag:zDNV5bDo+2Ts+LzNSQAG6w==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRkVLU1puU1hCbjJEV240\ndk16eCtNU3UvQ1dzeDVwYUUwY3c4SDl3dTJJCk5COHBvWDdYSmhMYVRvRXVOZ3JT\nZEZKZFRuMHBoT3lHWGxvSUdNdWZZWTAKLS0tIGxDS0lTOEhJUFd5ZFgxMUQrcXlr\nUVkrTUEzR0l4VUt1NFRVMFc3ZkMvVkUKy1ncnu8Ssyk0ySCz/STpAMsCJH/l10Y7\nOo8LyefnkC/JVwXBZorrVpPs4luGdaveH3BdK1TTXyvP9WuaJaze5w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-11-03T22:52:32Z",
		"mac": "ENC[AES256_GCM,data:bA1A7MutqRO1R9rmvpdubn5osAm4zYjLT0ob2BmQv/ioXx6FFcl4MiNGl3vQTCkvrODUhpBPcZLEGJpkOZAlM4OAeB9o4lgd3nx2wiLQ4s5JGovUggMqvo+YixFYcJknzTRWDWTXKBx7a5zLfbBPVLbVrdYXbJexHGANgmotfoE=,iv:xkQ6n/COVY3oH5iuhLilv3MuU7l665/zqfNkblwDhEk=,tag:WcfKvVAcJfNgXLtP4DnbaA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}