---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitmonero-pvc
  namespace: monero
  labels:
    app.kubernetes.io/name: &name monerod
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ceph-block
