---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app monerod
  namespace: monero
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: https://hub.docker.com/r/sethsimmons/simple-monerod
    args:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --public-node
      - --no-igd
      - --zmq-pub=tcp://0.0.0.0:18083
      - --enable-dns-blocklist
      - --prune-blockchain
      - --in-peers=50
      - --out-peers=50
    # additionalContainers:
    #   - name: tor
    #     image: goldy/tor-hidden-service
    #     tag: latest
    #     env:
    #       - name: MONEROD_TOR_SERVICE_HOSTS
    #         value: 18089:monerod:18089
    #       - name: MONEROD_TOR_SERVICE_VERSION
    #         value: 3
    #     nodeSelector:
    #       node-role.kubernetes.io/worker: "true"
    #     persistence:
    #       existingClaim: tor-keys
    #       mountPath: /var/lib/tor/hidden_service/
    service:
      main:
        ports:
          http:
            enabled: false
          p2p:
            enabled: true
            port: 18080
            targetPort: 18080
            protocol: TCP
          zmq:
            enabled: true
            port: 18083
            targetPort: 18083
            protocol: TCP
          rpc-restricted:
            enabled: true
            port: 18089
            targetPort: 18089
            protocol: TCP
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    persistence:
      bitmonero:
        enabled: true
        existingClaim: bitmonero
        mountPath: /home/monero/.bitmonero
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        memory: 500Mi
