---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
  namespace: default
spec:
  secretName: "${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: "${CLUSTER_CERT}"
    kind: ClusterIssuer
  commonName: "${PUBLIC_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
