---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whereabouts
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/whereabouts
      tag: v0.5.4

    cni:
      image:
        repository: ghcr.io/k8s-at-home/cni-plugins
        tag: v1.1.1

      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin

      version: "0.3.1"
