---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/v0.5.4/doc/crds/daemonset-install.yaml
  - ./ip-reconciler-job.yaml
