---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: networking
  name: &app uptimerobot-heartbeat
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
            - name: *app
              image: ghcr.io/onedr0p/kubernetes-kubectl:1.25.3
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - &scriptPath "/app/uptimerobot-heartbeat.sh"
              volumeMounts:
                - name: *app
                  mountPath: *scriptPath
                  subPath: &scriptName uptimerobot-heartbeat.sh
                  readOnly: true
          volumes:
            - name: *app
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: *app
                      items:
                        - key: *scriptName
                          path: *scriptName
