---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "wildcard-default-cert"
  namespace: networking
spec:
  privateKey:
    rotationPolicy: Always
  commonName: "${PUBLIC_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: "wildcard-default-cert-tls"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
