---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.24.5
      sourceRef:
        kind: HelmRepository
        name: project-calico-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    installation:
      enabled: true
      registry: quay.io
      imagePath: calico
      calicoNetwork:
        bgp: Enabled
        # hostPorts: Disabled
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 16
            cidr: "${NET_POD_CIDR}"
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()
        linuxDataplane: Iptables
        nodeAddressAutodetectionV4:
          cidrs:
            - "${NET_HOST_CIDR}"
      controlPlaneNodeSelector:
        node-role.kubernetes.io/worker: "true"
      controlPlaneTolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
