---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugin-operator
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.25.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  dependsOn:
    - name: node-feature-discovery
      namespace: system
  values:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"