# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XKn6NXHTKSfdURqacShEiPve9XXKHPx/jF+9645YBzIpEkajub6Zjg==,iv:nqS99ueMrEC0xYXQLrSBcXHyRTTsUnldd1bZQYfLosI=,tag:paYzgEJC8tsDAaWTMUQ3Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U3Z1M096ZmpRSVNUQ0Zu
            dWJnbW1HeTBtWW9xRGw4bStkZk84TkFJSzBrCnljdjh5Vjl0cjRCbGRyNmMwVzIr
            dDhKMmRuTzhZNjNGZHFEZURyY2RRY1kKLS0tIERyTUhJTlFncm5SZS9aQWZUNklz
            VEdXaFpUWTQxVXk0RTlXMDhmU0tNSVkKVC+qXIYsTWqmYckUaQWrW6y5H4zDI3jp
            PrRoS2tzg+GxrqO7XKMXZvTklEhFAr6HQXVTF47TgzDcXc+RBjBFUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-19T22:07:00Z"
    mac: ENC[AES256_GCM,data:admi6pJy0oCzs/I4JyPPGBrjt+WjdDNZAbmWBjXSQVplhPrxPWiJANtdfQq7pkbvDx5mYbnakEYMyaTHBNoa9jqVv4H71oDee+6RGzFPZAfC3j7SnvD8IgGuMe5vdAqaJzSTDuOvQ/beWaTq97UVWuoHVQkRX4uUPI7UF++UDEE=,iv:rGEO3AmScuERhqqwVkbSqpYxq808vVjuF5ALUG3O7s4=,tag:Azz0RWCql0mnYntZQlJFbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
