---
apiVersion: v1
kind: Service
metadata:
  name: kvm01
  namespace: networking
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kvm01
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.10.30
    ports:
      - port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kvm01
  namespace: networking
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # external-dns.home.arpa/enabled: "true"
    hajimari.io/enable: "true"
    hajimari.io/icon: "nas"
spec:
  tls:
    - hosts:
        - kvm01.${SECRET_DOMAIN}"
      secretName: "${CLUSTER_CERT_SECRET}"
  rules:
    - host: "kvm01.${SECRET_PRIVATE_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kvm01
                port:
                  number: 443
