---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data-pvc
  namespace: networking
  labels:
    app.kubernetes.io/name: &name omada-controller
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
