---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: kopia-config
    files:
      - ./config/repository.config
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/name: kopia
  app.kubernetes.io/instance: kopia
