---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: whereabouts-source
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/k8snetworkplumbingwg/whereabouts.git
  ref:
    tag: v0.5.4
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/doc/crds
    # exclude ip-reconciler-job
    # /doc/crds/ip-reconciler-job.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-whereabouts
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: whereabouts-source
