---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero-controller
  namespace: monero-system
spec:
  selector:
    matchLabels:
      app: monero-controller
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: monero-controller
    spec:
      serviceAccount: monero-controller
      containers:
        - name: monero-controller
          image: https://github.com/cirocosta/monero-operator/tree/master/cmd/monero-operator
          command: [monero-operator, operator]
          env:
            - name: TOR_SIDECAR_IMAGE
              value: https://github.com/cirocosta/monero-operator/tree/master/cmd/monero-operator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          annotations:
            kyverno.io/ignore: "true"
          nodeSelector:
            node-role.kubernetes.io/worker: "true"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              memory: 500Mi
