---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name bazarr
  namespace: media-automation
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
