---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media-servers
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: system
    - name: node-feature-discovery
      namespace: system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.29.1.6316-f4cdfea9c@sha256:0c41145101d045363337f6e49de8f5b52a20a22a24131031aafcf8841a6e16a4
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_PLEX_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
    podAnnotations:
      k8s.v1.cni.cncf.io/networks: networking/macvlan-conf
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/share/media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 10000Mi
