---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: reflector
      version: v6.1.47
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: reflector
