apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring,security,smart-home
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring,security,smart-home
stringData:
    username: ENC[AES256_GCM,data:mWBR5qAN2YA=,iv:NJvNFLpwSTmy3H7CLHw9Mu4yYNFjiFzfkk25SePuZL8=,tag:a69yYqRfgrDUli+SksdmeA==,type:str]
    password: ENC[AES256_GCM,data:CRfFaD3sCFwIB9mo4HDfOWV4o04=,iv:YQEPS/5syQ65M3snlotTXOOES4cxHmOsdarFEP1wXWI=,tag:5Kppol1Wd0Ns4yj0c0jXMQ==,type:str]
# ---
# kind: Secret
# apiVersion: v1
# type: Opaque
# metadata:
#     name: postgres-minio
#     namespace: databases
#     labels:
#         k8s.enterprisedb.io/reload: "true"
# stringData:
#     MINIO_ACCESS_KEY: ENC[AES256_GCM,data:OWJrAxtFI/UmfA==,iv:nQX4XX99PBWngbRD7cP5tvPGiQXPHGatlCxeRdeazok=,tag:K+KS7xw+J2noWxcy82spbA==,type:str]
#     MINIO_SECRET_KEY: ENC[AES256_GCM,data:8Mo8ZwRcAj1XKR/mxSlxK251RolrFgCfzWIA,iv:GLHP1UooFpiOAJqG7Jd6k/6LlKvyrzcItSpLRdRI0FI=,tag:VLRLkkY/u5iq0MTYR2IRyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdmhERTBPNll6eXBXbHdN
            endaMTZSK2dhSlByZ1N3RG5aUXNtVHp1ZFNJClE4Y01ITW9iV2hzWDhHcWRBMDZq
            VHZjaTBwQXNKUnQ0M1FmQ0Q4OUhiYncKLS0tIFozZEpKbzNhVWpRcEhaTmFmR0o4
            MThqcVl0L0F2Y2ZaMCtuTks3Nnh0YXMKTqeRwsdN6V2Zg6vllUuXeV8/6wR/xwmH
            F9+PLB4FSs2F4TqZgLPsATFdyoMq+EStSlq8dhSiQbj75gQFW1Wk5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T12:02:51Z"
    mac: ENC[AES256_GCM,data:LUz9OgFgRgC8HHykhwewrn0VulZ6GQhW2pIXCQ81AcYsvYTHc6OQ18UY2kfYBlOd8jk5m/YvbkHrVD0exBof+mQrguyjaw1vhwtdygvz86XWiQaS3BQST9Fqz2qGSJRpksTXW7OuyBPK1iLeBNfpemxzTGVGaxIRA4Ps5+EXUnQ=,iv:r++nCalaIn9GKZvu8CzC7DL/NvVVa/aTyvdfo0JSoF4=,tag:+oFkXnsx7epZriJB0rucvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
