apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:v1+DEg==,iv:OfopXynbYWAZn2NFsXbtFaSjjVrH4AORa3oeCXgn6so=,tag:O3PhkD3NYOJziqnzcfEEsQ==,type:str]
    password: ENC[AES256_GCM,data:CRfFaD3sCFwIB9mo4HDfOWV4o04=,iv:YQEPS/5syQ65M3snlotTXOOES4cxHmOsdarFEP1wXWI=,tag:5Kppol1Wd0Ns4yj0c0jXMQ==,type:str]
# ---
# kind: Secret
# apiVersion: v1
# type: Opaque
# metadata:
#     name: postgres-minio
#     namespace: default
#     labels:
#         k8s.enterprisedb.io/reload: "true"
# stringData:
#     MINIO_ACCESS_KEY: ENC[AES256_GCM,data:OWJrAxtFI/UmfA==,iv:nQX4XX99PBWngbRD7cP5tvPGiQXPHGatlCxeRdeazok=,tag:K+KS7xw+J2noWxcy82spbA==,type:str]
#     MINIO_SECRET_KEY: ENC[AES256_GCM,data:8Mo8ZwRcAj1XKR/mxSlxK251RolrFgCfzWIA,iv:GLHP1UooFpiOAJqG7Jd6k/6LlKvyrzcItSpLRdRI0FI=,tag:VLRLkkY/u5iq0MTYR2IRyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e22ys05jj0mvsmt4nll7p0gk567ksugx5v0tdufh968vdw9jn5mswhvw0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdmhERTBPNll6eXBXbHdN
            endaMTZSK2dhSlByZ1N3RG5aUXNtVHp1ZFNJClE4Y01ITW9iV2hzWDhHcWRBMDZq
            VHZjaTBwQXNKUnQ0M1FmQ0Q4OUhiYncKLS0tIFozZEpKbzNhVWpRcEhaTmFmR0o4
            MThqcVl0L0F2Y2ZaMCtuTks3Nnh0YXMKTqeRwsdN6V2Zg6vllUuXeV8/6wR/xwmH
            F9+PLB4FSs2F4TqZgLPsATFdyoMq+EStSlq8dhSiQbj75gQFW1Wk5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-16T20:23:45Z"
    mac: ENC[AES256_GCM,data:EbOxbzPbY984qpj7PcymO0Q5eCasWtnlBWFrzJLUBhYLwJEvTu5hrgGThGiVjoKr+VdsSX75FyOTxbHnR1pGB6QrCLz96lg4A6/RDppJAqrzD3zY9jg0dwdU4gSV3/53wKRTZSakCHly0uoCjFVkWhRkNsEH7qdSagtM81DnMy4=,iv:MgQymQ0Qr909VdMtVnteaQ9Rq0HMTzWbkmxyDlVOS/o=,tag:ZImK2eRQEuCed/0m/w8HxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
